#define ADD_LAUNCH_IDX 0
#define ADD_INPUT_A_IDX 1
#define ADD_INPUT_A_NDIM_IDX 2
#define ADD_INPUT_A_DIMS_IDX 3
#define ADD_INPUT_B_IDX 4
#define ADD_INPUT_B_NDIM_IDX 5
#define ADD_INPUT_B_DIMS_IDX 6
#define ADD_OUTPUT_C_IDX 7
#define ADD_OUTPUT_C_NDIM_IDX 8
#define ADD_OUTPUT_C_DIMS_IDX 9
#define ADD_TENSOR_NAME_IDX 10
#define AVERAGEPOOL_LAUNCH_IDX 11
#define AVERAGEPOOL_INPUT_X_IDX 12
#define AVERAGEPOOL_INPUT_X_NDIM_IDX 13
#define AVERAGEPOOL_INPUT_X_DIMS_IDX 14
#define AVERAGEPOOL_OUTPUT_Y_IDX 15
#define AVERAGEPOOL_OUTPUT_Y_NDIM_IDX 16
#define AVERAGEPOOL_OUTPUT_Y_DIMS_IDX 17
#define AVERAGEPOOL_AUTO_PAD_IDX 18
#define AVERAGEPOOL_COUNT_INCLUDE_PAD_IDX 19
#define AVERAGEPOOL_KERNEL_SHAPE_IDX 20
#define AVERAGEPOOL_NUMBER_OF_KERNEL_SHAPE_IDX 21
#define AVERAGEPOOL_PADS_IDX 22
#define AVERAGEPOOL_NUMBER_OF_PADS_IDX 23
#define AVERAGEPOOL_STRIDES_IDX 24
#define AVERAGEPOOL_NUMBER_OF_STRIDES_IDX 25
#define AVERAGEPOOL_TENSOR_NAME_IDX 26
#define BATCHNORMALIZATION_LAUNCH_IDX 27
#define BATCHNORMALIZATION_INPUT_X_IDX 28
#define BATCHNORMALIZATION_INPUT_X_NDIM_IDX 29
#define BATCHNORMALIZATION_INPUT_X_DIMS_IDX 30
#define BATCHNORMALIZATION_INPUT_SCALE_IDX 31
#define BATCHNORMALIZATION_INPUT_SCALE_NDIM_IDX 32
#define BATCHNORMALIZATION_INPUT_SCALE_DIMS_IDX 33
#define BATCHNORMALIZATION_INPUT_B_IDX 34
#define BATCHNORMALIZATION_INPUT_B_NDIM_IDX 35
#define BATCHNORMALIZATION_INPUT_B_DIMS_IDX 36
#define BATCHNORMALIZATION_INPUT_MEAN_IDX 37
#define BATCHNORMALIZATION_INPUT_MEAN_NDIM_IDX 38
#define BATCHNORMALIZATION_INPUT_MEAN_DIMS_IDX 39
#define BATCHNORMALIZATION_INPUT_VAR_IDX 40
#define BATCHNORMALIZATION_INPUT_VAR_NDIM_IDX 41
#define BATCHNORMALIZATION_INPUT_VAR_DIMS_IDX 42
#define BATCHNORMALIZATION_OUTPUT_Y_IDX 43
#define BATCHNORMALIZATION_OUTPUT_Y_NDIM_IDX 44
#define BATCHNORMALIZATION_OUTPUT_Y_DIMS_IDX 45
#define BATCHNORMALIZATION_OUTPUT_MEAN_IDX 46
#define BATCHNORMALIZATION_OUTPUT_MEAN_NDIM_IDX 47
#define BATCHNORMALIZATION_OUTPUT_MEAN_DIMS_IDX 48
#define BATCHNORMALIZATION_OUTPUT_VAR_IDX 49
#define BATCHNORMALIZATION_OUTPUT_VAR_NDIM_IDX 50
#define BATCHNORMALIZATION_OUTPUT_VAR_DIMS_IDX 51
#define BATCHNORMALIZATION_OUTPUT_SAVED_MEAN_IDX 52
#define BATCHNORMALIZATION_OUTPUT_SAVED_MEAN_NDIM_IDX 53
#define BATCHNORMALIZATION_OUTPUT_SAVED_MEAN_DIMS_IDX 54
#define BATCHNORMALIZATION_OUTPUT_SAVED_VAR_IDX 55
#define BATCHNORMALIZATION_OUTPUT_SAVED_VAR_NDIM_IDX 56
#define BATCHNORMALIZATION_OUTPUT_SAVED_VAR_DIMS_IDX 57
#define BATCHNORMALIZATION_EPSILON_IDX 58
#define BATCHNORMALIZATION_MOMENTUM_IDX 59
#define BATCHNORMALIZATION_SPATIAL_IDX 60
#define BATCHNORMALIZATION_TENSOR_NAME_IDX 61
#define CONCAT_LAUNCH_IDX 62
#define CONCAT_INPUT_INPUTS_IDX 63
#define CONCAT_INPUT_INPUTS_NTENSOR_IDX 64
#define CONCAT_INPUT_INPUTS_NDIM_IDX 65
#define CONCAT_INPUT_INPUTS_DIMS_IDX 66
#define CONCAT_OUTPUT_CONCAT_RESULT_IDX 67
#define CONCAT_OUTPUT_CONCAT_RESULT_NDIM_IDX 68
#define CONCAT_OUTPUT_CONCAT_RESULT_DIMS_IDX 69
#define CONCAT_AXIS_IDX 70
#define CONCAT_TENSOR_NAME_IDX 71
#define CONV_LAUNCH_IDX 72
#define CONV_INPUT_X_IDX 73
#define CONV_INPUT_X_NDIM_IDX 74
#define CONV_INPUT_X_DIMS_IDX 75
#define CONV_INPUT_W_IDX 76
#define CONV_INPUT_W_NDIM_IDX 77
#define CONV_INPUT_W_DIMS_IDX 78
#define CONV_INPUT_B_IDX 79
#define CONV_INPUT_B_NDIM_IDX 80
#define CONV_INPUT_B_DIMS_IDX 81
#define CONV_OUTPUT_Y_IDX 82
#define CONV_OUTPUT_Y_NDIM_IDX 83
#define CONV_OUTPUT_Y_DIMS_IDX 84
#define CONV_AUTO_PAD_IDX 85
#define CONV_DILATIONS_IDX 86
#define CONV_NUMBER_OF_DILATIONS_IDX 87
#define CONV_GROUP_IDX 88
#define CONV_KERNEL_SHAPE_IDX 89
#define CONV_NUMBER_OF_KERNEL_SHAPE_IDX 90
#define CONV_PADS_IDX 91
#define CONV_NUMBER_OF_PADS_IDX 92
#define CONV_STRIDES_IDX 93
#define CONV_NUMBER_OF_STRIDES_IDX 94
#define CONV_TENSOR_NAME_IDX 95
#define GEMM_LAUNCH_IDX 96
#define GEMM_INPUT_A_IDX 97
#define GEMM_INPUT_A_NDIM_IDX 98
#define GEMM_INPUT_A_DIMS_IDX 99
#define GEMM_INPUT_B_IDX 100
#define GEMM_INPUT_B_NDIM_IDX 101
#define GEMM_INPUT_B_DIMS_IDX 102
#define GEMM_INPUT_C_IDX 103
#define GEMM_INPUT_C_NDIM_IDX 104
#define GEMM_INPUT_C_DIMS_IDX 105
#define GEMM_OUTPUT_Y_IDX 106
#define GEMM_OUTPUT_Y_NDIM_IDX 107
#define GEMM_OUTPUT_Y_DIMS_IDX 108
#define GEMM_ALPHA_IDX 109
#define GEMM_BETA_IDX 110
#define GEMM_TRANSA_IDX 111
#define GEMM_TRANSB_IDX 112
#define GEMM_TENSOR_NAME_IDX 113
#define GLOBALAVERAGEPOOL_LAUNCH_IDX 114
#define GLOBALAVERAGEPOOL_INPUT_X_IDX 115
#define GLOBALAVERAGEPOOL_INPUT_X_NDIM_IDX 116
#define GLOBALAVERAGEPOOL_INPUT_X_DIMS_IDX 117
#define GLOBALAVERAGEPOOL_OUTPUT_Y_IDX 118
#define GLOBALAVERAGEPOOL_OUTPUT_Y_NDIM_IDX 119
#define GLOBALAVERAGEPOOL_OUTPUT_Y_DIMS_IDX 120
#define GLOBALAVERAGEPOOL_TENSOR_NAME_IDX 121
#define LRN_LAUNCH_IDX 122
#define LRN_INPUT_X_IDX 123
#define LRN_INPUT_X_NDIM_IDX 124
#define LRN_INPUT_X_DIMS_IDX 125
#define LRN_OUTPUT_Y_IDX 126
#define LRN_OUTPUT_Y_NDIM_IDX 127
#define LRN_OUTPUT_Y_DIMS_IDX 128
#define LRN_ALPHA_IDX 129
#define LRN_BETA_IDX 130
#define LRN_BIAS_IDX 131
#define LRN_SIZE_IDX 132
#define LRN_TENSOR_NAME_IDX 133
#define MAXPOOL_LAUNCH_IDX 134
#define MAXPOOL_INPUT_X_IDX 135
#define MAXPOOL_INPUT_X_NDIM_IDX 136
#define MAXPOOL_INPUT_X_DIMS_IDX 137
#define MAXPOOL_OUTPUT_Y_IDX 138
#define MAXPOOL_OUTPUT_Y_NDIM_IDX 139
#define MAXPOOL_OUTPUT_Y_DIMS_IDX 140
#define MAXPOOL_OUTPUT_INDICES_IDX 141
#define MAXPOOL_OUTPUT_INDICES_NDIM_IDX 142
#define MAXPOOL_OUTPUT_INDICES_DIMS_IDX 143
#define MAXPOOL_AUTO_PAD_IDX 144
#define MAXPOOL_KERNEL_SHAPE_IDX 145
#define MAXPOOL_NUMBER_OF_KERNEL_SHAPE_IDX 146
#define MAXPOOL_PADS_IDX 147
#define MAXPOOL_NUMBER_OF_PADS_IDX 148
#define MAXPOOL_STORAGE_ORDER_IDX 149
#define MAXPOOL_STRIDES_IDX 150
#define MAXPOOL_NUMBER_OF_STRIDES_IDX 151
#define MAXPOOL_TENSOR_NAME_IDX 152
#define MUL_LAUNCH_IDX 153
#define MUL_INPUT_A_IDX 154
#define MUL_INPUT_A_NDIM_IDX 155
#define MUL_INPUT_A_DIMS_IDX 156
#define MUL_INPUT_B_IDX 157
#define MUL_INPUT_B_NDIM_IDX 158
#define MUL_INPUT_B_DIMS_IDX 159
#define MUL_OUTPUT_C_IDX 160
#define MUL_OUTPUT_C_NDIM_IDX 161
#define MUL_OUTPUT_C_DIMS_IDX 162
#define MUL_TENSOR_NAME_IDX 163
#define RELU_LAUNCH_IDX 164
#define RELU_INPUT_X_IDX 165
#define RELU_INPUT_X_NDIM_IDX 166
#define RELU_INPUT_X_DIMS_IDX 167
#define RELU_OUTPUT_Y_IDX 168
#define RELU_OUTPUT_Y_NDIM_IDX 169
#define RELU_OUTPUT_Y_DIMS_IDX 170
#define RELU_TENSOR_NAME_IDX 171
#define RESHAPE_LAUNCH_IDX 172
#define RESHAPE_INPUT_DATA_IDX 173
#define RESHAPE_INPUT_DATA_NDIM_IDX 174
#define RESHAPE_INPUT_DATA_DIMS_IDX 175
#define RESHAPE_INPUT_SHAPE_IDX 176
#define RESHAPE_INPUT_SHAPE_NDIM_IDX 177
#define RESHAPE_INPUT_SHAPE_DIMS_IDX 178
#define RESHAPE_OUTPUT_RESHAPED_IDX 179
#define RESHAPE_OUTPUT_RESHAPED_NDIM_IDX 180
#define RESHAPE_OUTPUT_RESHAPED_DIMS_IDX 181
#define RESHAPE_TENSOR_NAME_IDX 182
#define SOFTMAX_LAUNCH_IDX 183
#define SOFTMAX_INPUT_INPUT_IDX 184
#define SOFTMAX_INPUT_INPUT_NDIM_IDX 185
#define SOFTMAX_INPUT_INPUT_DIMS_IDX 186
#define SOFTMAX_OUTPUT_OUTPUT_IDX 187
#define SOFTMAX_OUTPUT_OUTPUT_NDIM_IDX 188
#define SOFTMAX_OUTPUT_OUTPUT_DIMS_IDX 189
#define SOFTMAX_AXIS_IDX 190
#define SOFTMAX_TENSOR_NAME_IDX 191
#define SUM_LAUNCH_IDX 192
#define SUM_INPUT_DATA_0_IDX 193
#define SUM_INPUT_DATA_0_NTENSOR_IDX 194
#define SUM_INPUT_DATA_0_NDIM_IDX 195
#define SUM_INPUT_DATA_0_DIMS_IDX 196
#define SUM_OUTPUT_SUM_IDX 197
#define SUM_OUTPUT_SUM_NDIM_IDX 198
#define SUM_OUTPUT_SUM_DIMS_IDX 199
#define SUM_TENSOR_NAME_IDX 200
#define TRANSPOSE_LAUNCH_IDX 201
#define TRANSPOSE_INPUT_DATA_IDX 202
#define TRANSPOSE_INPUT_DATA_NDIM_IDX 203
#define TRANSPOSE_INPUT_DATA_DIMS_IDX 204
#define TRANSPOSE_OUTPUT_TRANSPOSED_IDX 205
#define TRANSPOSE_OUTPUT_TRANSPOSED_NDIM_IDX 206
#define TRANSPOSE_OUTPUT_TRANSPOSED_DIMS_IDX 207
#define TRANSPOSE_PERM_IDX 208
#define TRANSPOSE_NUMBER_OF_PERM_IDX 209
#define TRANSPOSE_TENSOR_NAME_IDX 210
#define UNSQUEEZE_LAUNCH_IDX 211
#define UNSQUEEZE_INPUT_DATA_IDX 212
#define UNSQUEEZE_INPUT_DATA_NDIM_IDX 213
#define UNSQUEEZE_INPUT_DATA_DIMS_IDX 214
#define UNSQUEEZE_OUTPUT_EXPANDED_IDX 215
#define UNSQUEEZE_OUTPUT_EXPANDED_NDIM_IDX 216
#define UNSQUEEZE_OUTPUT_EXPANDED_DIMS_IDX 217
#define UNSQUEEZE_AXES_IDX 218
#define UNSQUEEZE_NUMBER_OF_AXES_IDX 219
#define UNSQUEEZE_TENSOR_NAME_IDX 220
#define ADD_LAUNCH_ADDR (FASTMODEL_REG_START_ADDR | ADD_LAUNCH_IDX << 2)
#define ADD_INPUT_A_ADDR (FASTMODEL_REG_START_ADDR | ADD_INPUT_A_IDX << 2)
#define ADD_INPUT_A_NDIM_ADDR (FASTMODEL_REG_START_ADDR | ADD_INPUT_A_NDIM_IDX << 2)
#define ADD_INPUT_A_DIMS_ADDR (FASTMODEL_REG_START_ADDR | ADD_INPUT_A_DIMS_IDX << 2)
#define ADD_INPUT_B_ADDR (FASTMODEL_REG_START_ADDR | ADD_INPUT_B_IDX << 2)
#define ADD_INPUT_B_NDIM_ADDR (FASTMODEL_REG_START_ADDR | ADD_INPUT_B_NDIM_IDX << 2)
#define ADD_INPUT_B_DIMS_ADDR (FASTMODEL_REG_START_ADDR | ADD_INPUT_B_DIMS_IDX << 2)
#define ADD_OUTPUT_C_ADDR (FASTMODEL_REG_START_ADDR | ADD_OUTPUT_C_IDX << 2)
#define ADD_OUTPUT_C_NDIM_ADDR (FASTMODEL_REG_START_ADDR | ADD_OUTPUT_C_NDIM_IDX << 2)
#define ADD_OUTPUT_C_DIMS_ADDR (FASTMODEL_REG_START_ADDR | ADD_OUTPUT_C_DIMS_IDX << 2)
#define ADD_TENSOR_NAME_ADDR (FASTMODEL_REG_START_ADDR | ADD_TENSOR_NAME_IDX << 2)
#define AVERAGEPOOL_LAUNCH_ADDR (FASTMODEL_REG_START_ADDR | AVERAGEPOOL_LAUNCH_IDX << 2)
#define AVERAGEPOOL_INPUT_X_ADDR (FASTMODEL_REG_START_ADDR | AVERAGEPOOL_INPUT_X_IDX << 2)
#define AVERAGEPOOL_INPUT_X_NDIM_ADDR (FASTMODEL_REG_START_ADDR | AVERAGEPOOL_INPUT_X_NDIM_IDX << 2)
#define AVERAGEPOOL_INPUT_X_DIMS_ADDR (FASTMODEL_REG_START_ADDR | AVERAGEPOOL_INPUT_X_DIMS_IDX << 2)
#define AVERAGEPOOL_OUTPUT_Y_ADDR (FASTMODEL_REG_START_ADDR | AVERAGEPOOL_OUTPUT_Y_IDX << 2)
#define AVERAGEPOOL_OUTPUT_Y_NDIM_ADDR (FASTMODEL_REG_START_ADDR | AVERAGEPOOL_OUTPUT_Y_NDIM_IDX << 2)
#define AVERAGEPOOL_OUTPUT_Y_DIMS_ADDR (FASTMODEL_REG_START_ADDR | AVERAGEPOOL_OUTPUT_Y_DIMS_IDX << 2)
#define AVERAGEPOOL_AUTO_PAD_ADDR (FASTMODEL_REG_START_ADDR | AVERAGEPOOL_AUTO_PAD_IDX << 2)
#define AVERAGEPOOL_COUNT_INCLUDE_PAD_ADDR (FASTMODEL_REG_START_ADDR | AVERAGEPOOL_COUNT_INCLUDE_PAD_IDX << 2)
#define AVERAGEPOOL_KERNEL_SHAPE_ADDR (FASTMODEL_REG_START_ADDR | AVERAGEPOOL_KERNEL_SHAPE_IDX << 2)
#define AVERAGEPOOL_NUMBER_OF_KERNEL_SHAPE_ADDR (FASTMODEL_REG_START_ADDR | AVERAGEPOOL_NUMBER_OF_KERNEL_SHAPE_IDX << 2)
#define AVERAGEPOOL_PADS_ADDR (FASTMODEL_REG_START_ADDR | AVERAGEPOOL_PADS_IDX << 2)
#define AVERAGEPOOL_NUMBER_OF_PADS_ADDR (FASTMODEL_REG_START_ADDR | AVERAGEPOOL_NUMBER_OF_PADS_IDX << 2)
#define AVERAGEPOOL_STRIDES_ADDR (FASTMODEL_REG_START_ADDR | AVERAGEPOOL_STRIDES_IDX << 2)
#define AVERAGEPOOL_NUMBER_OF_STRIDES_ADDR (FASTMODEL_REG_START_ADDR | AVERAGEPOOL_NUMBER_OF_STRIDES_IDX << 2)
#define AVERAGEPOOL_TENSOR_NAME_ADDR (FASTMODEL_REG_START_ADDR | AVERAGEPOOL_TENSOR_NAME_IDX << 2)
#define BATCHNORMALIZATION_LAUNCH_ADDR (FASTMODEL_REG_START_ADDR | BATCHNORMALIZATION_LAUNCH_IDX << 2)
#define BATCHNORMALIZATION_INPUT_X_ADDR (FASTMODEL_REG_START_ADDR | BATCHNORMALIZATION_INPUT_X_IDX << 2)
#define BATCHNORMALIZATION_INPUT_X_NDIM_ADDR (FASTMODEL_REG_START_ADDR | BATCHNORMALIZATION_INPUT_X_NDIM_IDX << 2)
#define BATCHNORMALIZATION_INPUT_X_DIMS_ADDR (FASTMODEL_REG_START_ADDR | BATCHNORMALIZATION_INPUT_X_DIMS_IDX << 2)
#define BATCHNORMALIZATION_INPUT_SCALE_ADDR (FASTMODEL_REG_START_ADDR | BATCHNORMALIZATION_INPUT_SCALE_IDX << 2)
#define BATCHNORMALIZATION_INPUT_SCALE_NDIM_ADDR (FASTMODEL_REG_START_ADDR | BATCHNORMALIZATION_INPUT_SCALE_NDIM_IDX << 2)
#define BATCHNORMALIZATION_INPUT_SCALE_DIMS_ADDR (FASTMODEL_REG_START_ADDR | BATCHNORMALIZATION_INPUT_SCALE_DIMS_IDX << 2)
#define BATCHNORMALIZATION_INPUT_B_ADDR (FASTMODEL_REG_START_ADDR | BATCHNORMALIZATION_INPUT_B_IDX << 2)
#define BATCHNORMALIZATION_INPUT_B_NDIM_ADDR (FASTMODEL_REG_START_ADDR | BATCHNORMALIZATION_INPUT_B_NDIM_IDX << 2)
#define BATCHNORMALIZATION_INPUT_B_DIMS_ADDR (FASTMODEL_REG_START_ADDR | BATCHNORMALIZATION_INPUT_B_DIMS_IDX << 2)
#define BATCHNORMALIZATION_INPUT_MEAN_ADDR (FASTMODEL_REG_START_ADDR | BATCHNORMALIZATION_INPUT_MEAN_IDX << 2)
#define BATCHNORMALIZATION_INPUT_MEAN_NDIM_ADDR (FASTMODEL_REG_START_ADDR | BATCHNORMALIZATION_INPUT_MEAN_NDIM_IDX << 2)
#define BATCHNORMALIZATION_INPUT_MEAN_DIMS_ADDR (FASTMODEL_REG_START_ADDR | BATCHNORMALIZATION_INPUT_MEAN_DIMS_IDX << 2)
#define BATCHNORMALIZATION_INPUT_VAR_ADDR (FASTMODEL_REG_START_ADDR | BATCHNORMALIZATION_INPUT_VAR_IDX << 2)
#define BATCHNORMALIZATION_INPUT_VAR_NDIM_ADDR (FASTMODEL_REG_START_ADDR | BATCHNORMALIZATION_INPUT_VAR_NDIM_IDX << 2)
#define BATCHNORMALIZATION_INPUT_VAR_DIMS_ADDR (FASTMODEL_REG_START_ADDR | BATCHNORMALIZATION_INPUT_VAR_DIMS_IDX << 2)
#define BATCHNORMALIZATION_OUTPUT_Y_ADDR (FASTMODEL_REG_START_ADDR | BATCHNORMALIZATION_OUTPUT_Y_IDX << 2)
#define BATCHNORMALIZATION_OUTPUT_Y_NDIM_ADDR (FASTMODEL_REG_START_ADDR | BATCHNORMALIZATION_OUTPUT_Y_NDIM_IDX << 2)
#define BATCHNORMALIZATION_OUTPUT_Y_DIMS_ADDR (FASTMODEL_REG_START_ADDR | BATCHNORMALIZATION_OUTPUT_Y_DIMS_IDX << 2)
#define BATCHNORMALIZATION_OUTPUT_MEAN_ADDR (FASTMODEL_REG_START_ADDR | BATCHNORMALIZATION_OUTPUT_MEAN_IDX << 2)
#define BATCHNORMALIZATION_OUTPUT_MEAN_NDIM_ADDR (FASTMODEL_REG_START_ADDR | BATCHNORMALIZATION_OUTPUT_MEAN_NDIM_IDX << 2)
#define BATCHNORMALIZATION_OUTPUT_MEAN_DIMS_ADDR (FASTMODEL_REG_START_ADDR | BATCHNORMALIZATION_OUTPUT_MEAN_DIMS_IDX << 2)
#define BATCHNORMALIZATION_OUTPUT_VAR_ADDR (FASTMODEL_REG_START_ADDR | BATCHNORMALIZATION_OUTPUT_VAR_IDX << 2)
#define BATCHNORMALIZATION_OUTPUT_VAR_NDIM_ADDR (FASTMODEL_REG_START_ADDR | BATCHNORMALIZATION_OUTPUT_VAR_NDIM_IDX << 2)
#define BATCHNORMALIZATION_OUTPUT_VAR_DIMS_ADDR (FASTMODEL_REG_START_ADDR | BATCHNORMALIZATION_OUTPUT_VAR_DIMS_IDX << 2)
#define BATCHNORMALIZATION_OUTPUT_SAVED_MEAN_ADDR (FASTMODEL_REG_START_ADDR | BATCHNORMALIZATION_OUTPUT_SAVED_MEAN_IDX << 2)
#define BATCHNORMALIZATION_OUTPUT_SAVED_MEAN_NDIM_ADDR (FASTMODEL_REG_START_ADDR | BATCHNORMALIZATION_OUTPUT_SAVED_MEAN_NDIM_IDX << 2)
#define BATCHNORMALIZATION_OUTPUT_SAVED_MEAN_DIMS_ADDR (FASTMODEL_REG_START_ADDR | BATCHNORMALIZATION_OUTPUT_SAVED_MEAN_DIMS_IDX << 2)
#define BATCHNORMALIZATION_OUTPUT_SAVED_VAR_ADDR (FASTMODEL_REG_START_ADDR | BATCHNORMALIZATION_OUTPUT_SAVED_VAR_IDX << 2)
#define BATCHNORMALIZATION_OUTPUT_SAVED_VAR_NDIM_ADDR (FASTMODEL_REG_START_ADDR | BATCHNORMALIZATION_OUTPUT_SAVED_VAR_NDIM_IDX << 2)
#define BATCHNORMALIZATION_OUTPUT_SAVED_VAR_DIMS_ADDR (FASTMODEL_REG_START_ADDR | BATCHNORMALIZATION_OUTPUT_SAVED_VAR_DIMS_IDX << 2)
#define BATCHNORMALIZATION_EPSILON_ADDR (FASTMODEL_REG_START_ADDR | BATCHNORMALIZATION_EPSILON_IDX << 2)
#define BATCHNORMALIZATION_MOMENTUM_ADDR (FASTMODEL_REG_START_ADDR | BATCHNORMALIZATION_MOMENTUM_IDX << 2)
#define BATCHNORMALIZATION_SPATIAL_ADDR (FASTMODEL_REG_START_ADDR | BATCHNORMALIZATION_SPATIAL_IDX << 2)
#define BATCHNORMALIZATION_TENSOR_NAME_ADDR (FASTMODEL_REG_START_ADDR | BATCHNORMALIZATION_TENSOR_NAME_IDX << 2)
#define CONCAT_LAUNCH_ADDR (FASTMODEL_REG_START_ADDR | CONCAT_LAUNCH_IDX << 2)
#define CONCAT_INPUT_INPUTS_ADDR (FASTMODEL_REG_START_ADDR | CONCAT_INPUT_INPUTS_IDX << 2)
#define CONCAT_INPUT_INPUTS_NTENSOR_ADDR (FASTMODEL_REG_START_ADDR | CONCAT_INPUT_INPUTS_NTENSOR_IDX << 2)
#define CONCAT_INPUT_INPUTS_NDIM_ADDR (FASTMODEL_REG_START_ADDR | CONCAT_INPUT_INPUTS_NDIM_IDX << 2)
#define CONCAT_INPUT_INPUTS_DIMS_ADDR (FASTMODEL_REG_START_ADDR | CONCAT_INPUT_INPUTS_DIMS_IDX << 2)
#define CONCAT_OUTPUT_CONCAT_RESULT_ADDR (FASTMODEL_REG_START_ADDR | CONCAT_OUTPUT_CONCAT_RESULT_IDX << 2)
#define CONCAT_OUTPUT_CONCAT_RESULT_NDIM_ADDR (FASTMODEL_REG_START_ADDR | CONCAT_OUTPUT_CONCAT_RESULT_NDIM_IDX << 2)
#define CONCAT_OUTPUT_CONCAT_RESULT_DIMS_ADDR (FASTMODEL_REG_START_ADDR | CONCAT_OUTPUT_CONCAT_RESULT_DIMS_IDX << 2)
#define CONCAT_AXIS_ADDR (FASTMODEL_REG_START_ADDR | CONCAT_AXIS_IDX << 2)
#define CONCAT_TENSOR_NAME_ADDR (FASTMODEL_REG_START_ADDR | CONCAT_TENSOR_NAME_IDX << 2)
#define CONV_LAUNCH_ADDR (FASTMODEL_REG_START_ADDR | CONV_LAUNCH_IDX << 2)
#define CONV_INPUT_X_ADDR (FASTMODEL_REG_START_ADDR | CONV_INPUT_X_IDX << 2)
#define CONV_INPUT_X_NDIM_ADDR (FASTMODEL_REG_START_ADDR | CONV_INPUT_X_NDIM_IDX << 2)
#define CONV_INPUT_X_DIMS_ADDR (FASTMODEL_REG_START_ADDR | CONV_INPUT_X_DIMS_IDX << 2)
#define CONV_INPUT_W_ADDR (FASTMODEL_REG_START_ADDR | CONV_INPUT_W_IDX << 2)
#define CONV_INPUT_W_NDIM_ADDR (FASTMODEL_REG_START_ADDR | CONV_INPUT_W_NDIM_IDX << 2)
#define CONV_INPUT_W_DIMS_ADDR (FASTMODEL_REG_START_ADDR | CONV_INPUT_W_DIMS_IDX << 2)
#define CONV_INPUT_B_ADDR (FASTMODEL_REG_START_ADDR | CONV_INPUT_B_IDX << 2)
#define CONV_INPUT_B_NDIM_ADDR (FASTMODEL_REG_START_ADDR | CONV_INPUT_B_NDIM_IDX << 2)
#define CONV_INPUT_B_DIMS_ADDR (FASTMODEL_REG_START_ADDR | CONV_INPUT_B_DIMS_IDX << 2)
#define CONV_OUTPUT_Y_ADDR (FASTMODEL_REG_START_ADDR | CONV_OUTPUT_Y_IDX << 2)
#define CONV_OUTPUT_Y_NDIM_ADDR (FASTMODEL_REG_START_ADDR | CONV_OUTPUT_Y_NDIM_IDX << 2)
#define CONV_OUTPUT_Y_DIMS_ADDR (FASTMODEL_REG_START_ADDR | CONV_OUTPUT_Y_DIMS_IDX << 2)
#define CONV_AUTO_PAD_ADDR (FASTMODEL_REG_START_ADDR | CONV_AUTO_PAD_IDX << 2)
#define CONV_DILATIONS_ADDR (FASTMODEL_REG_START_ADDR | CONV_DILATIONS_IDX << 2)
#define CONV_NUMBER_OF_DILATIONS_ADDR (FASTMODEL_REG_START_ADDR | CONV_NUMBER_OF_DILATIONS_IDX << 2)
#define CONV_GROUP_ADDR (FASTMODEL_REG_START_ADDR | CONV_GROUP_IDX << 2)
#define CONV_KERNEL_SHAPE_ADDR (FASTMODEL_REG_START_ADDR | CONV_KERNEL_SHAPE_IDX << 2)
#define CONV_NUMBER_OF_KERNEL_SHAPE_ADDR (FASTMODEL_REG_START_ADDR | CONV_NUMBER_OF_KERNEL_SHAPE_IDX << 2)
#define CONV_PADS_ADDR (FASTMODEL_REG_START_ADDR | CONV_PADS_IDX << 2)
#define CONV_NUMBER_OF_PADS_ADDR (FASTMODEL_REG_START_ADDR | CONV_NUMBER_OF_PADS_IDX << 2)
#define CONV_STRIDES_ADDR (FASTMODEL_REG_START_ADDR | CONV_STRIDES_IDX << 2)
#define CONV_NUMBER_OF_STRIDES_ADDR (FASTMODEL_REG_START_ADDR | CONV_NUMBER_OF_STRIDES_IDX << 2)
#define CONV_TENSOR_NAME_ADDR (FASTMODEL_REG_START_ADDR | CONV_TENSOR_NAME_IDX << 2)
#define GEMM_LAUNCH_ADDR (FASTMODEL_REG_START_ADDR | GEMM_LAUNCH_IDX << 2)
#define GEMM_INPUT_A_ADDR (FASTMODEL_REG_START_ADDR | GEMM_INPUT_A_IDX << 2)
#define GEMM_INPUT_A_NDIM_ADDR (FASTMODEL_REG_START_ADDR | GEMM_INPUT_A_NDIM_IDX << 2)
#define GEMM_INPUT_A_DIMS_ADDR (FASTMODEL_REG_START_ADDR | GEMM_INPUT_A_DIMS_IDX << 2)
#define GEMM_INPUT_B_ADDR (FASTMODEL_REG_START_ADDR | GEMM_INPUT_B_IDX << 2)
#define GEMM_INPUT_B_NDIM_ADDR (FASTMODEL_REG_START_ADDR | GEMM_INPUT_B_NDIM_IDX << 2)
#define GEMM_INPUT_B_DIMS_ADDR (FASTMODEL_REG_START_ADDR | GEMM_INPUT_B_DIMS_IDX << 2)
#define GEMM_INPUT_C_ADDR (FASTMODEL_REG_START_ADDR | GEMM_INPUT_C_IDX << 2)
#define GEMM_INPUT_C_NDIM_ADDR (FASTMODEL_REG_START_ADDR | GEMM_INPUT_C_NDIM_IDX << 2)
#define GEMM_INPUT_C_DIMS_ADDR (FASTMODEL_REG_START_ADDR | GEMM_INPUT_C_DIMS_IDX << 2)
#define GEMM_OUTPUT_Y_ADDR (FASTMODEL_REG_START_ADDR | GEMM_OUTPUT_Y_IDX << 2)
#define GEMM_OUTPUT_Y_NDIM_ADDR (FASTMODEL_REG_START_ADDR | GEMM_OUTPUT_Y_NDIM_IDX << 2)
#define GEMM_OUTPUT_Y_DIMS_ADDR (FASTMODEL_REG_START_ADDR | GEMM_OUTPUT_Y_DIMS_IDX << 2)
#define GEMM_ALPHA_ADDR (FASTMODEL_REG_START_ADDR | GEMM_ALPHA_IDX << 2)
#define GEMM_BETA_ADDR (FASTMODEL_REG_START_ADDR | GEMM_BETA_IDX << 2)
#define GEMM_TRANSA_ADDR (FASTMODEL_REG_START_ADDR | GEMM_TRANSA_IDX << 2)
#define GEMM_TRANSB_ADDR (FASTMODEL_REG_START_ADDR | GEMM_TRANSB_IDX << 2)
#define GEMM_TENSOR_NAME_ADDR (FASTMODEL_REG_START_ADDR | GEMM_TENSOR_NAME_IDX << 2)
#define GLOBALAVERAGEPOOL_LAUNCH_ADDR (FASTMODEL_REG_START_ADDR | GLOBALAVERAGEPOOL_LAUNCH_IDX << 2)
#define GLOBALAVERAGEPOOL_INPUT_X_ADDR (FASTMODEL_REG_START_ADDR | GLOBALAVERAGEPOOL_INPUT_X_IDX << 2)
#define GLOBALAVERAGEPOOL_INPUT_X_NDIM_ADDR (FASTMODEL_REG_START_ADDR | GLOBALAVERAGEPOOL_INPUT_X_NDIM_IDX << 2)
#define GLOBALAVERAGEPOOL_INPUT_X_DIMS_ADDR (FASTMODEL_REG_START_ADDR | GLOBALAVERAGEPOOL_INPUT_X_DIMS_IDX << 2)
#define GLOBALAVERAGEPOOL_OUTPUT_Y_ADDR (FASTMODEL_REG_START_ADDR | GLOBALAVERAGEPOOL_OUTPUT_Y_IDX << 2)
#define GLOBALAVERAGEPOOL_OUTPUT_Y_NDIM_ADDR (FASTMODEL_REG_START_ADDR | GLOBALAVERAGEPOOL_OUTPUT_Y_NDIM_IDX << 2)
#define GLOBALAVERAGEPOOL_OUTPUT_Y_DIMS_ADDR (FASTMODEL_REG_START_ADDR | GLOBALAVERAGEPOOL_OUTPUT_Y_DIMS_IDX << 2)
#define GLOBALAVERAGEPOOL_TENSOR_NAME_ADDR (FASTMODEL_REG_START_ADDR | GLOBALAVERAGEPOOL_TENSOR_NAME_IDX << 2)
#define LRN_LAUNCH_ADDR (FASTMODEL_REG_START_ADDR | LRN_LAUNCH_IDX << 2)
#define LRN_INPUT_X_ADDR (FASTMODEL_REG_START_ADDR | LRN_INPUT_X_IDX << 2)
#define LRN_INPUT_X_NDIM_ADDR (FASTMODEL_REG_START_ADDR | LRN_INPUT_X_NDIM_IDX << 2)
#define LRN_INPUT_X_DIMS_ADDR (FASTMODEL_REG_START_ADDR | LRN_INPUT_X_DIMS_IDX << 2)
#define LRN_OUTPUT_Y_ADDR (FASTMODEL_REG_START_ADDR | LRN_OUTPUT_Y_IDX << 2)
#define LRN_OUTPUT_Y_NDIM_ADDR (FASTMODEL_REG_START_ADDR | LRN_OUTPUT_Y_NDIM_IDX << 2)
#define LRN_OUTPUT_Y_DIMS_ADDR (FASTMODEL_REG_START_ADDR | LRN_OUTPUT_Y_DIMS_IDX << 2)
#define LRN_ALPHA_ADDR (FASTMODEL_REG_START_ADDR | LRN_ALPHA_IDX << 2)
#define LRN_BETA_ADDR (FASTMODEL_REG_START_ADDR | LRN_BETA_IDX << 2)
#define LRN_BIAS_ADDR (FASTMODEL_REG_START_ADDR | LRN_BIAS_IDX << 2)
#define LRN_SIZE_ADDR (FASTMODEL_REG_START_ADDR | LRN_SIZE_IDX << 2)
#define LRN_TENSOR_NAME_ADDR (FASTMODEL_REG_START_ADDR | LRN_TENSOR_NAME_IDX << 2)
#define MAXPOOL_LAUNCH_ADDR (FASTMODEL_REG_START_ADDR | MAXPOOL_LAUNCH_IDX << 2)
#define MAXPOOL_INPUT_X_ADDR (FASTMODEL_REG_START_ADDR | MAXPOOL_INPUT_X_IDX << 2)
#define MAXPOOL_INPUT_X_NDIM_ADDR (FASTMODEL_REG_START_ADDR | MAXPOOL_INPUT_X_NDIM_IDX << 2)
#define MAXPOOL_INPUT_X_DIMS_ADDR (FASTMODEL_REG_START_ADDR | MAXPOOL_INPUT_X_DIMS_IDX << 2)
#define MAXPOOL_OUTPUT_Y_ADDR (FASTMODEL_REG_START_ADDR | MAXPOOL_OUTPUT_Y_IDX << 2)
#define MAXPOOL_OUTPUT_Y_NDIM_ADDR (FASTMODEL_REG_START_ADDR | MAXPOOL_OUTPUT_Y_NDIM_IDX << 2)
#define MAXPOOL_OUTPUT_Y_DIMS_ADDR (FASTMODEL_REG_START_ADDR | MAXPOOL_OUTPUT_Y_DIMS_IDX << 2)
#define MAXPOOL_OUTPUT_INDICES_ADDR (FASTMODEL_REG_START_ADDR | MAXPOOL_OUTPUT_INDICES_IDX << 2)
#define MAXPOOL_OUTPUT_INDICES_NDIM_ADDR (FASTMODEL_REG_START_ADDR | MAXPOOL_OUTPUT_INDICES_NDIM_IDX << 2)
#define MAXPOOL_OUTPUT_INDICES_DIMS_ADDR (FASTMODEL_REG_START_ADDR | MAXPOOL_OUTPUT_INDICES_DIMS_IDX << 2)
#define MAXPOOL_AUTO_PAD_ADDR (FASTMODEL_REG_START_ADDR | MAXPOOL_AUTO_PAD_IDX << 2)
#define MAXPOOL_KERNEL_SHAPE_ADDR (FASTMODEL_REG_START_ADDR | MAXPOOL_KERNEL_SHAPE_IDX << 2)
#define MAXPOOL_NUMBER_OF_KERNEL_SHAPE_ADDR (FASTMODEL_REG_START_ADDR | MAXPOOL_NUMBER_OF_KERNEL_SHAPE_IDX << 2)
#define MAXPOOL_PADS_ADDR (FASTMODEL_REG_START_ADDR | MAXPOOL_PADS_IDX << 2)
#define MAXPOOL_NUMBER_OF_PADS_ADDR (FASTMODEL_REG_START_ADDR | MAXPOOL_NUMBER_OF_PADS_IDX << 2)
#define MAXPOOL_STORAGE_ORDER_ADDR (FASTMODEL_REG_START_ADDR | MAXPOOL_STORAGE_ORDER_IDX << 2)
#define MAXPOOL_STRIDES_ADDR (FASTMODEL_REG_START_ADDR | MAXPOOL_STRIDES_IDX << 2)
#define MAXPOOL_NUMBER_OF_STRIDES_ADDR (FASTMODEL_REG_START_ADDR | MAXPOOL_NUMBER_OF_STRIDES_IDX << 2)
#define MAXPOOL_TENSOR_NAME_ADDR (FASTMODEL_REG_START_ADDR | MAXPOOL_TENSOR_NAME_IDX << 2)
#define MUL_LAUNCH_ADDR (FASTMODEL_REG_START_ADDR | MUL_LAUNCH_IDX << 2)
#define MUL_INPUT_A_ADDR (FASTMODEL_REG_START_ADDR | MUL_INPUT_A_IDX << 2)
#define MUL_INPUT_A_NDIM_ADDR (FASTMODEL_REG_START_ADDR | MUL_INPUT_A_NDIM_IDX << 2)
#define MUL_INPUT_A_DIMS_ADDR (FASTMODEL_REG_START_ADDR | MUL_INPUT_A_DIMS_IDX << 2)
#define MUL_INPUT_B_ADDR (FASTMODEL_REG_START_ADDR | MUL_INPUT_B_IDX << 2)
#define MUL_INPUT_B_NDIM_ADDR (FASTMODEL_REG_START_ADDR | MUL_INPUT_B_NDIM_IDX << 2)
#define MUL_INPUT_B_DIMS_ADDR (FASTMODEL_REG_START_ADDR | MUL_INPUT_B_DIMS_IDX << 2)
#define MUL_OUTPUT_C_ADDR (FASTMODEL_REG_START_ADDR | MUL_OUTPUT_C_IDX << 2)
#define MUL_OUTPUT_C_NDIM_ADDR (FASTMODEL_REG_START_ADDR | MUL_OUTPUT_C_NDIM_IDX << 2)
#define MUL_OUTPUT_C_DIMS_ADDR (FASTMODEL_REG_START_ADDR | MUL_OUTPUT_C_DIMS_IDX << 2)
#define MUL_TENSOR_NAME_ADDR (FASTMODEL_REG_START_ADDR | MUL_TENSOR_NAME_IDX << 2)
#define RELU_LAUNCH_ADDR (FASTMODEL_REG_START_ADDR | RELU_LAUNCH_IDX << 2)
#define RELU_INPUT_X_ADDR (FASTMODEL_REG_START_ADDR | RELU_INPUT_X_IDX << 2)
#define RELU_INPUT_X_NDIM_ADDR (FASTMODEL_REG_START_ADDR | RELU_INPUT_X_NDIM_IDX << 2)
#define RELU_INPUT_X_DIMS_ADDR (FASTMODEL_REG_START_ADDR | RELU_INPUT_X_DIMS_IDX << 2)
#define RELU_OUTPUT_Y_ADDR (FASTMODEL_REG_START_ADDR | RELU_OUTPUT_Y_IDX << 2)
#define RELU_OUTPUT_Y_NDIM_ADDR (FASTMODEL_REG_START_ADDR | RELU_OUTPUT_Y_NDIM_IDX << 2)
#define RELU_OUTPUT_Y_DIMS_ADDR (FASTMODEL_REG_START_ADDR | RELU_OUTPUT_Y_DIMS_IDX << 2)
#define RELU_TENSOR_NAME_ADDR (FASTMODEL_REG_START_ADDR | RELU_TENSOR_NAME_IDX << 2)
#define RESHAPE_LAUNCH_ADDR (FASTMODEL_REG_START_ADDR | RESHAPE_LAUNCH_IDX << 2)
#define RESHAPE_INPUT_DATA_ADDR (FASTMODEL_REG_START_ADDR | RESHAPE_INPUT_DATA_IDX << 2)
#define RESHAPE_INPUT_DATA_NDIM_ADDR (FASTMODEL_REG_START_ADDR | RESHAPE_INPUT_DATA_NDIM_IDX << 2)
#define RESHAPE_INPUT_DATA_DIMS_ADDR (FASTMODEL_REG_START_ADDR | RESHAPE_INPUT_DATA_DIMS_IDX << 2)
#define RESHAPE_INPUT_SHAPE_ADDR (FASTMODEL_REG_START_ADDR | RESHAPE_INPUT_SHAPE_IDX << 2)
#define RESHAPE_INPUT_SHAPE_NDIM_ADDR (FASTMODEL_REG_START_ADDR | RESHAPE_INPUT_SHAPE_NDIM_IDX << 2)
#define RESHAPE_INPUT_SHAPE_DIMS_ADDR (FASTMODEL_REG_START_ADDR | RESHAPE_INPUT_SHAPE_DIMS_IDX << 2)
#define RESHAPE_OUTPUT_RESHAPED_ADDR (FASTMODEL_REG_START_ADDR | RESHAPE_OUTPUT_RESHAPED_IDX << 2)
#define RESHAPE_OUTPUT_RESHAPED_NDIM_ADDR (FASTMODEL_REG_START_ADDR | RESHAPE_OUTPUT_RESHAPED_NDIM_IDX << 2)
#define RESHAPE_OUTPUT_RESHAPED_DIMS_ADDR (FASTMODEL_REG_START_ADDR | RESHAPE_OUTPUT_RESHAPED_DIMS_IDX << 2)
#define RESHAPE_TENSOR_NAME_ADDR (FASTMODEL_REG_START_ADDR | RESHAPE_TENSOR_NAME_IDX << 2)
#define SOFTMAX_LAUNCH_ADDR (FASTMODEL_REG_START_ADDR | SOFTMAX_LAUNCH_IDX << 2)
#define SOFTMAX_INPUT_INPUT_ADDR (FASTMODEL_REG_START_ADDR | SOFTMAX_INPUT_INPUT_IDX << 2)
#define SOFTMAX_INPUT_INPUT_NDIM_ADDR (FASTMODEL_REG_START_ADDR | SOFTMAX_INPUT_INPUT_NDIM_IDX << 2)
#define SOFTMAX_INPUT_INPUT_DIMS_ADDR (FASTMODEL_REG_START_ADDR | SOFTMAX_INPUT_INPUT_DIMS_IDX << 2)
#define SOFTMAX_OUTPUT_OUTPUT_ADDR (FASTMODEL_REG_START_ADDR | SOFTMAX_OUTPUT_OUTPUT_IDX << 2)
#define SOFTMAX_OUTPUT_OUTPUT_NDIM_ADDR (FASTMODEL_REG_START_ADDR | SOFTMAX_OUTPUT_OUTPUT_NDIM_IDX << 2)
#define SOFTMAX_OUTPUT_OUTPUT_DIMS_ADDR (FASTMODEL_REG_START_ADDR | SOFTMAX_OUTPUT_OUTPUT_DIMS_IDX << 2)
#define SOFTMAX_AXIS_ADDR (FASTMODEL_REG_START_ADDR | SOFTMAX_AXIS_IDX << 2)
#define SOFTMAX_TENSOR_NAME_ADDR (FASTMODEL_REG_START_ADDR | SOFTMAX_TENSOR_NAME_IDX << 2)
#define SUM_LAUNCH_ADDR (FASTMODEL_REG_START_ADDR | SUM_LAUNCH_IDX << 2)
#define SUM_INPUT_DATA_0_ADDR (FASTMODEL_REG_START_ADDR | SUM_INPUT_DATA_0_IDX << 2)
#define SUM_INPUT_DATA_0_NTENSOR_ADDR (FASTMODEL_REG_START_ADDR | SUM_INPUT_DATA_0_NTENSOR_IDX << 2)
#define SUM_INPUT_DATA_0_NDIM_ADDR (FASTMODEL_REG_START_ADDR | SUM_INPUT_DATA_0_NDIM_IDX << 2)
#define SUM_INPUT_DATA_0_DIMS_ADDR (FASTMODEL_REG_START_ADDR | SUM_INPUT_DATA_0_DIMS_IDX << 2)
#define SUM_OUTPUT_SUM_ADDR (FASTMODEL_REG_START_ADDR | SUM_OUTPUT_SUM_IDX << 2)
#define SUM_OUTPUT_SUM_NDIM_ADDR (FASTMODEL_REG_START_ADDR | SUM_OUTPUT_SUM_NDIM_IDX << 2)
#define SUM_OUTPUT_SUM_DIMS_ADDR (FASTMODEL_REG_START_ADDR | SUM_OUTPUT_SUM_DIMS_IDX << 2)
#define SUM_TENSOR_NAME_ADDR (FASTMODEL_REG_START_ADDR | SUM_TENSOR_NAME_IDX << 2)
#define TRANSPOSE_LAUNCH_ADDR (FASTMODEL_REG_START_ADDR | TRANSPOSE_LAUNCH_IDX << 2)
#define TRANSPOSE_INPUT_DATA_ADDR (FASTMODEL_REG_START_ADDR | TRANSPOSE_INPUT_DATA_IDX << 2)
#define TRANSPOSE_INPUT_DATA_NDIM_ADDR (FASTMODEL_REG_START_ADDR | TRANSPOSE_INPUT_DATA_NDIM_IDX << 2)
#define TRANSPOSE_INPUT_DATA_DIMS_ADDR (FASTMODEL_REG_START_ADDR | TRANSPOSE_INPUT_DATA_DIMS_IDX << 2)
#define TRANSPOSE_OUTPUT_TRANSPOSED_ADDR (FASTMODEL_REG_START_ADDR | TRANSPOSE_OUTPUT_TRANSPOSED_IDX << 2)
#define TRANSPOSE_OUTPUT_TRANSPOSED_NDIM_ADDR (FASTMODEL_REG_START_ADDR | TRANSPOSE_OUTPUT_TRANSPOSED_NDIM_IDX << 2)
#define TRANSPOSE_OUTPUT_TRANSPOSED_DIMS_ADDR (FASTMODEL_REG_START_ADDR | TRANSPOSE_OUTPUT_TRANSPOSED_DIMS_IDX << 2)
#define TRANSPOSE_PERM_ADDR (FASTMODEL_REG_START_ADDR | TRANSPOSE_PERM_IDX << 2)
#define TRANSPOSE_NUMBER_OF_PERM_ADDR (FASTMODEL_REG_START_ADDR | TRANSPOSE_NUMBER_OF_PERM_IDX << 2)
#define TRANSPOSE_TENSOR_NAME_ADDR (FASTMODEL_REG_START_ADDR | TRANSPOSE_TENSOR_NAME_IDX << 2)
#define UNSQUEEZE_LAUNCH_ADDR (FASTMODEL_REG_START_ADDR | UNSQUEEZE_LAUNCH_IDX << 2)
#define UNSQUEEZE_INPUT_DATA_ADDR (FASTMODEL_REG_START_ADDR | UNSQUEEZE_INPUT_DATA_IDX << 2)
#define UNSQUEEZE_INPUT_DATA_NDIM_ADDR (FASTMODEL_REG_START_ADDR | UNSQUEEZE_INPUT_DATA_NDIM_IDX << 2)
#define UNSQUEEZE_INPUT_DATA_DIMS_ADDR (FASTMODEL_REG_START_ADDR | UNSQUEEZE_INPUT_DATA_DIMS_IDX << 2)
#define UNSQUEEZE_OUTPUT_EXPANDED_ADDR (FASTMODEL_REG_START_ADDR | UNSQUEEZE_OUTPUT_EXPANDED_IDX << 2)
#define UNSQUEEZE_OUTPUT_EXPANDED_NDIM_ADDR (FASTMODEL_REG_START_ADDR | UNSQUEEZE_OUTPUT_EXPANDED_NDIM_IDX << 2)
#define UNSQUEEZE_OUTPUT_EXPANDED_DIMS_ADDR (FASTMODEL_REG_START_ADDR | UNSQUEEZE_OUTPUT_EXPANDED_DIMS_IDX << 2)
#define UNSQUEEZE_AXES_ADDR (FASTMODEL_REG_START_ADDR | UNSQUEEZE_AXES_IDX << 2)
#define UNSQUEEZE_NUMBER_OF_AXES_ADDR (FASTMODEL_REG_START_ADDR | UNSQUEEZE_NUMBER_OF_AXES_IDX << 2)
#define UNSQUEEZE_TENSOR_NAME_ADDR (FASTMODEL_REG_START_ADDR | UNSQUEEZE_TENSOR_NAME_IDX << 2)
